spring.application.name=fincore-bank
server.port=${PORT:8081}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bank_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:Abhi@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:9f44c9c0ae9b4f5ea281d79c2d48f7a9c1e61735b0f22a60dfd1c1ba9275f9d1}
jwt.expiration=${JWT_EXPIRATION:86400000}

